### ISSUE TITLE
flavour description

### ISSUE THREAD

**Issue by edmundlaugasson** [etais-ee/etais-web#2]
Would kindly ask to add a flavour description. Could not find at http://etais.ee/self_service/#adding-a-vm

EDIT: looks like duplicate of #3 , so closed the issue here

**Comment by livenson** [comment]
Reopenning, as flavors and images are different aspects.

**Comment by livenson** [comment]
WIP: 1f0f7043d33dea9679d8f29fff1cdbcee89e7806
