### ISSUE TITLE
Add description of images provided by ETAIS OpenStacks

### ISSUE THREAD

**Issue by livenson** [etais-ee/etais-web#3]
- login details (users, etc)
- packer buildscript?

**Comment by edmundlaugasson** [comment]
would appreciate also details about:
* CLI only or also GUI
* when GUI then which desktop environment (DE)

Some lightweight DE's would be useful (e.g. MATE, XFCE, LXDE or similar), could be installed certainly by own.
Packer buildscript would be also great.
